### ISSUE TITLE
update npm for latest release

### ISSUE THREAD

**Issue by rodryquintero** [austinksmith/Hamsters.js#12]
You can only install version 3.7 from NPM.

**Comment by austinksmith** [comment]
I apologize, there hasn't been a new official release in a little while as I've been busy with other projects. I'd recommend cloning the dev branch and using that as it has the latest changes. In the next release I will update the npm version as well.

**Comment by austinksmith** [comment]
I apologize for the late response the last two weeks have been extremely busy.
