### ISSUE TITLE
Hamsters.js Doesn't Work In A Loop With Multiple Threads?

### ISSUE THREAD

**Issue by eddiendi** [austinksmith/Hamsters.js#14]
In a loop Hamsters seems to take a vector/array and split it across the threads available but does not aggregate the results to one final output - the output is per thread ONLY. For instance, if you multiply an array like [1,2,3,4,5] with the scalar 2, the array is split into two threads (assuming a duo-core machine) with data [1,2, 3] and [4,5] respectively, which ends up with two separate arrays... i.e. [2,4,6] and [8,10] AND NOT [2,4,6,8,10] as I expected. See code below. 

How can we AGGREGATE MULTIPLE threads output BACK INTO ONE array? BUT more peculiarly, ONLY the first (or one) thread actually returns the expected result, the other thread(s) do not seem to always return correct results - unless ONLY if threads is set to 1, which defeats the value of using multiple cores/parallelism. It doesn't matter even if I use tools (hamsters.tools.loop) the results returned are wrong. Is this a bug?

var matrix = [
            [1,2,3,4,5],
            [1,2,3,4,5]
        ];
        var i;

```
    for (i = 0; i < matrix.length; i += 1) {
        try {
            var j, dotprod = 0, matrix_row = matrix[i];
            for (j = 0; j < matrix_row.length; j += 1) {
                dotprod += (matrix_row[j] * 2);
            }
            console.log("Vanilla-output:" + dotprod);

            var params = {'array': matrix_row};
            hamsters.run(params, function () {
                var arr = params.array;
                var dotprod = [];
                arr.forEach(function (item) {
                    dotprod.push(item * item);
                });
                console.log("each-thread:" + dotprod);
                rtn.data = dotprod;
            }, function (results) {
                var output = 0;
               console.log("Hamsters-aggregation:" + results);
                results.forEach(function (item) {
                    output += item;
                });
                console.log("Hamsters-summation:" + output);
            }, hamsters.maxThreads, true, 'Float32');

        } catch (err) {
            console.log(err);
        }
    }
```

**Comment by austinksmith** [comment]
In order to begin debugging this you need to remove your vanilla output from your hamsters output entirely, these should be logically separate test cases entirely.

**Comment by austinksmith** [comment]
To address your first question, I'm not entirely sure what your goal is in regards to aggregation as you're using the library incorrectly in several places. Issue number one is your logic inside the thread does *NOT* match the logic for your vanilla output. So your expectation to get the same results is well..unrealistic. Issue number two is that you are replacing rtn.data with your dotprod array inside the thread which is not the way to use the library, you need to push data to rtn.data do not replace rtn.data...

```
for (i = 0; i < matrix.length; i += 1) {
    var j, dotprod = 0, matrix_row = matrix[i];
    for (j = 0; j < matrix_row.length; j += 1) {
        dotprod += (matrix_row[j] * 2);
    }
    console.log("Vanilla-output:" + dotprod);

    var params = {'array': matrix_row};
    hamsters.run(params, function () {
        var arr = params.array;
        var dotprod = 0;
        for (j = 0; j < arr.length; j += 1) {
            dotprod += (arr[j] * 2);
        }
        rtn.data.push(dotprod);
    }, function (results) {
        var output = 0;
       console.log("Hamsters-aggregation:" + results);
        results.forEach(function (item) {
            output += item;
        });
        console.log("Hamsters-summation:" + output);
    }, 2, true, 'Float32');
}
```

These both result in the same output for me.

**Comment by austinksmith** [comment]
Additionally you shouldn't be using `hamsters.maxThreads` unless you know 100% that your data set is large enough to be divisible by the maximum number of threads or the default maximum of 4. That will result in errors and you should always limit the amount of threads you are running across to the best case for your dataset.

**Comment by austinksmith** [comment]
Finally you shouldn't be looping through your array of subarrays and expecting the library to aggregate your subarrays this way. The library expects a single array ie.`[1,2,3,4,5,1,2,3,4,5]`when you define multiple threads the library is expecting to have an array to split. Which would result in your current version of `var matrix`. You need to rethink how you approach this problem as you're not using the library as it's intended to be used, nor are your example test cases very well written to ensure nothing else is happening before it's handed off to hamsters.

**Comment by austinksmith** [comment]
Closing this now, thanks @eddiendi
