### ISSUE TITLE
Provide NPM Package

### ISSUE THREAD

**Issue by MichaReiser** [austinksmith/Hamsters.js#15]
Would it be possible to publish the library to npm?

**Comment by austinksmith** [comment]
The library is actually on npm it's just not updated with the latest version, I'll have to do that sometime here soon but I've been in the middle of moving and started a new gig so I haven't had time to focus on that lately

**Comment by nathansmyth** [comment]
+1 when you get the time.

Thank you so much for making this library. I really appreciate it!

**Comment by austinksmith** [comment]
Try this https://www.npmjs.com/package/hamsters.js let me know if you have any trouble. The old version was published under https://www.npmjs.com/package/webhamsters

**Comment by austinksmith** [comment]
I went ahead and published v3.9.6 as a new release that includes all the changes, NPM has been updated with this version as well and is working under their runkit link, seriously if there are any problems using it within Node let me know I don't do much node work and so I haven't really gone out of my way to officially test and support it. https://runkit.com/npm/hamsters.js

**Comment by austinksmith** [comment]
Closing this as it's resolved now.
