### ISSUE TITLE
hamsters.run does not work with not typed arrays

### ISSUE THREAD

**Issue by MichaReiser** [austinksmith/Hamsters.js#16]
Hamsters.run always tries to convert a given array to a typed array... even if it is not!. The problem is, that Hamsters.run assigns dataType = "na" if no data type has been given. 

However, feedHamster uses transferables when dataType is truthy (what now always is the case).

**Comment by austinksmith** [comment]
Thanks I went ahead and resolved this in dev branch, I'm pushing a hotfix release for this today and will comment with that link here in a few minutes.

**Comment by austinksmith** [comment]
Thanks @MichaReiser this is now resolved in this release https://github.com/austinksmith/Hamsters.js/releases/tag/v3.9.1
