### ISSUE TITLE
How do i use hamster.js to calculate fibonacci?What's wrong with my code?

### ISSUE THREAD

**Issue by renxin111** [austinksmith/Hamsters.js#19]
function test(){
  var params = {'array':[0,1,2,3,4,5,6,7,8,9]};
  hamsters.run(params, function() {
      for(var i = 2;i<params.array.length;i++)
	{
	     params.array[i]= params.array[i-1]+params.array[i-2];
	     rtn.data.push(params.array[i]);
	}
  }, function(output) {
    console.log(output) 
    return output;
  }, 4 , true);
}

**Comment by austinksmith** [comment]
Unfortunately this isn't the appropriate place to post a question like this, you should start with a function that doesn't use the library first and once you've verified that is working then try to port it to make use of `Hamsters.js` after reading the readme, thanks.

**Comment by austinksmith** [comment]
If you already have a working example feel free to share it and I'll try to guide you on the right path, I apologize I just don't have the bandwidth to provide support this way unless there is something wrong with the library functionality that needs addressed. In the library specs there is an example that computes the Fibonacci sequence though it's not a perfect example by any means it should give you a good baseline.
