### ISSUE TITLE
Visual Studio Bower package manager - cannot found package "Hamsters"

### ISSUE THREAD

**Issue by acterhd** [austinksmith/Hamsters.js#21]
Hello. I trying search package "Hamsters", "WebHamsters", but Visual Studio 2015 (JavaScript Project, Bower packages, all right) can not found this library. Try to fix this issue. Also, can not found in preview versions.

**Comment by austinksmith** [comment]
I removed the bower version for webhamsters recently and I think replaced it with a hamstersjs one, the bower file might be out of date, I remember bower giving me trouble trying to update that. I'll have to get some free time again to resolve the issue.

**Comment by austinksmith** [comment]
Sorry for the late response, try running `bower info hamsters.js` I went ahead and published the latest version to bower, the old package was under `webhamsters` so you might have to run that.

Marking this as resolved, thanks @acterhd
