### ISSUE TITLE
Documentation working example

### ISSUE THREAD

**Issue by cozzbie** [austinksmith/Hamsters.js#22]
Do you have some sort working example for this? I really do not understand the origin of your "rtn" variable and how outputs are passed back to the main thread.

**Comment by austinksmith** [comment]
The documentation should have working example logic, what is the issue you're encountering? You can see a working demo @ https://hamsters.io/performance

**Comment by cozzbie** [comment]
In the examples in the readme theres the passing of values to "rtn". Where is that declared? Hos is that accessed? @austinksmith

**Comment by austinksmith** [comment]
RTN is an internal variable, you can pass data into the RTN.data array, think of it like "Return data", it's not something you need to explicitly declare yourself. Simply push your output to rtn.data eg. `rtn.data.push(result);`

**Comment by cozzbie** [comment]
Sigh. I guess thats the issue then. I am using this with typescript and getting all kinds of errors. DANG!!! @austinksmith

**Comment by cozzbie** [comment]
So I am trying to run a keypair algo `let pair = keypair()` using this because the process is very memory tasking but I am having some issue passing or accessing the data into hammers scope. On the one hand when I do try to pass the value via the hammer params, it throws a cannot clone object error and I cannot access the value from the scope and understandably so...contexts are different. So what will be the best way to work with this? @austinksmith

**Comment by cozzbie** [comment]
`hamsters.run([keypair], //from the keypair lib import
                function () {
                    console.log(this.params[0]);
                    this.rtn.data.push(this.params[0]());
                },
                function (out) {
                    let pair = out[0][0];
                    console.log("Hammy out", pair);
                }, 1, false);`

![screen shot 2017-02-08 at 4 49 42 pm](https://cloud.githubusercontent.com/assets/3672236/22744972/43356982-ee1f-11e6-9bd6-4f5241fc5734.png)

@austinksmith

**Comment by cozzbie** [comment]
Me again. How can we include external npm libraries in the execution scope?

**Comment by austinksmith** [comment]
@cozzbie I'm not sure what you're trying to accomplish here?

Take a look at the documentation, you're not passing your parameters right at all. Your params need to be an object and your object needs to contain your array of data.

eg. `params = {'array': [keypair]}`

<img width="932" alt="screen shot 2017-02-08 at 7 25 38 pm" src="https://cloud.githubusercontent.com/assets/2227747/22763715/6d21106a-ee34-11e6-89b8-2062f1db91b2.png">

**Comment by austinksmith** [comment]
I'm not entirely sure what you mean by include external npm libraries, you would have to manually edit your version of the library and edit the logic that defines what exists inside a worker, you can then make the worker logic `import foo;`, that's handled on line 425, add your import before the `self.processDataType = function(dataType, buffer) {` line and your worker will have the import just like you would do on the main thread

**Comment by cozzbie** [comment]
Okidoks...thanks alot.

**Comment by austinksmith** [comment]
Closing this as I think it's resolved, thanks @cozzbie
