### ISSUE TITLE
Help processing data

### ISSUE THREAD

**Issue by SacrilegeTx** [austinksmith/Hamsters.js#24]
Hello, I need some help with my code.

Problem: 
I adapted the code to the library's form and when I run it the problem is the conditional run first and then the threads. The correct way is when threads is finished pass the next code line which what is the conditional.

[See the code in Pastebin website](http://pastebin.com/NZi8yGmr)
[Click here to view the Image](http://imgur.com/a/3ufDn)

Am I doing wrong something? 
Hope help me. (sorry for my english)
Ima newbie with web workers.

**Comment by austinksmith** [comment]
Sorry I can't provide any assistance without this being in a reproducible environment. Can you add it to https://jsfiddle.net/

**Comment by austinksmith** [comment]
So I'm going to close this issue out as I think you might have resolved your issue. Asynchronous code is sometimes (usually) hard to deal with, especially multi-threaded asynchronous code. I believe what you are saying is that you expect this function to be processed last.

```
        if (arrayPuntosLlantas_A.length > 1) {
            console.log('Get points from Coords');
            obtainPointsFromCoords(arrayPuntosLlantas_A);
        } else {
            console.log('There is no points in array:', arrayPuntosLlantas_A.length)
        }
```

You should probably just wrap this in a function and then call your function at the end of your callback.

```
function checkResults() {
         if (arrayPuntosLlantas_A.length > 1) {
            console.log('Get points from Coords');
            obtainPointsFromCoords(arrayPuntosLlantas_A);
        } else {
            console.log('There is no points in array:', arrayPuntosLlantas_A.length)
        }
}
```

And then add `checkResults();` at the end of your callback like this. 

```
 }, function(output) {
                output.forEach(function (item) {
                    if (isPointInPolygon(polygon, point = {x: item.x, y: item.y})) {
                        console.log('x:', item.x, 'y:', item.y, 'inside: ', isPointInPolygon(polygon, point = {x: item.x, y: item.y}));
                        lineasCompactacion(item.x, item.y, item.equipo, "A");
                    }
                      });
                 **checkResults();**
            }, 4, true);
```
