### ISSUE TITLE
Is there any way to pass a function to be executed inside hamster.run?

### ISSUE THREAD

**Issue by elviraux** [austinksmith/Hamsters.js#25]
Something kind of this https://jsfiddle.net/m82v751c/3/

**Comment by austinksmith** [comment]
Yes its actually really easy just not immediately obvious, you'll want to do something like this.

´´´
var params = {
  array: [],
  func: "body of function as a string"
};
hamsters.run(params, function(){
 var function = new Function(params.func);
 .....
 ......
});
´´´

You'll want to make sure your params function is only the inside of your function you should not need to include "function {do stuff}" just "do stuff".

**Comment by austinksmith** [comment]
I responded on mobile so the formatting might be messed up but that should work for you.

**Comment by austinksmith** [comment]
I'm closing this issue, thanks @elviraux

**Comment by austinksmith** [comment]
@elviraux I should mention the library already makes use of a `params.func` inside of a thread so in the event you want to pass a custom function you really don't need to manually specify `new Function(params.func)` as the library is already going to do that for you granted you're using the traditional `hamsters.run` and not the `hamsters.tools.loop` in which case you'd want to use a different naming convention like `params.mycustomfunction`

**Comment by darkworks** [comment]
```
var params = {
  array: [],
  func: "body of function as a string"
};
hamsters.run(params, function(){
 var function = new Function(params.func);
 .....
 ......
});
```


you said 
` func: "body of function as a string"`

so what about the parameters which are passed to function 

can you tell how to pass function along parameters of function .
