### ISSUE TITLE
navigator.hardwareConcurrency is undefined

### ISSUE THREAD

**Issue by rsmithsa** [austinksmith/Hamsters.js#29]
On my machine, when running (v4.1.1) in Edge "navigator.hardwareConcurrency" is undefined but "navigator" is defined.

During init if I don't explicitly specify "maxThreads" hamsters crashes.

I.e. We get in here and maxThreads is set to undefined:
```
 function setupHamstersEnvironment(onSuccess) {
....
    if(typeof navigator !== 'undefined') {
      hamsters.maxThreads = navigator.hardwareConcurrency;
    }

....
}
```

There should probably be an additional test, something like this:
```
 function setupHamstersEnvironment(onSuccess) {
....
    if(typeof navigator !== 'undefined' && typeof navigator.hardwareConcurrency !== 'undefined') {
      hamsters.maxThreads = navigator.hardwareConcurrency;
    }

....
}
```

**Comment by austinksmith** [comment]
Thanks for submitting this, I'm in the process of completely rewriting the library for the next release to make it more compatible and extensible in node etc. Can you tell me what version of Edge you're running? According to this Edge 15+ should support `navigator.hardwareConcurrency` unless they removed support for it.

https://github.com/MicrosoftEdge/Status/issues/99

**Comment by austinksmith** [comment]
According to Microsofts developer page they show Edge supporting this feature so it seems inconsistent on their page and the build shown in the link below was just released in December and I know I've used it in Edge since before then so maybe this is both a lack of being careful enough on my part and Microsoft adding/dropping support randomly?

https://developer.microsoft.com/en-us/microsoft-edge/platform/status/hardwareconcurrency/?q=hardwareC

**Comment by artem-vladimirov** [comment]
@austinksmith sorry, I didn't found if the lib allow the access to DOM in threads?

**Comment by rsmithsa** [comment]
I'm running: "Microsoft Edge 38.14393.1066.0" It might be random from Microsoft's side or it might be specific to my particular hardware?

**Comment by austinksmith** [comment]
@artem-vladimirov Please make a new ticket for issues not related to this one, thanks.

**Comment by austinksmith** [comment]
It shouldn't have anything to do with your hardware but just for sanity sake what is your hardware setup and are you running windows 10?

**Comment by rsmithsa** [comment]
Windows 10 Pro, Mecer Laptop,  i7 4712MQ, 24gb ram

**Comment by austinksmith** [comment]
Alright, please give this release a try and let me know if you encounter any other issues. 

https://github.com/austinksmith/Hamsters.js/releases/tag/v4.1.2

**Comment by rsmithsa** [comment]
Thanks, that resolves the issue
