### ISSUE TITLE
4.1.2 Doesn't spawn threads in browser

### ISSUE THREAD

**Issue by lelong37** [austinksmith/Hamsters.js#30]
For some reason when updating from 4.1.1 to 4.1.2, In 4.1.1. and running the same code with hamsters.js in node.js and in browser (Angular v4) app, both places code worked fine. However, with 4.1.2, seems browser does not spin up threads anymore.

**Comment by austinksmith** [comment]
Can you provide some example logic?

4.1.2 is running in the browser on the official site @ http://hamsters.io/performance

**Comment by austinksmith** [comment]
@lelong37 I am closing this issue, if you have further issues please make a new ticket. Thanks!

**Comment by lelong37** [comment]
Thanks seems to work now, not sure what the issue was, and thanks to the team for such an awesome package. :)
