### ISSUE TITLE
Task output is leaked after run ends.

### ISSUE THREAD

**Issue by rsmithsa** [austinksmith/Hamsters.js#31]
I've got a situation where I've got about 400mb of output data in Float64Arrays. This is retained and not GC's between runs.

I've put together a very simple fix for this but haven't tested with memoisation.

**Comment by austinksmith** [comment]
Let's do some fine tuned profiling to make sure this is really a memory leak, as far as I can tell the browser should garbage collect the task.

We can see that task is created like so.

```js
    var task = hamsters.wheel.newTask(hamsters.wheel.tasks.length, workers, order, dataType, fn, callback); 
```

hamsters.wheel.newTask looks like the following.

```js
  hamsters.wheel.newTask = function(taskid, workers, order, dataType, fn, cb) {
    hamsters.wheel.tasks.push({
      id: taskid,
      workers: [],
      count: 0,
      threads: workers, 
      input: [],
      dataType: dataType || null,
      fn: fn,
      output: [], 
      order: order || null,
      callback: cb
    });
    return hamsters.wheel.tasks[taskid];
  };
```

So every instance of task should be the same task object that is contained within hamsters.wheel.tasks which on line 559 we have the following which is called only when all threads have completed.
```js
  hamsters.wheel.tasks[task.id] = null; //Clean up our task, not needed any longer
```

Therefore the garbage collector *should* I believe clean that object up at some point right?

**Comment by austinksmith** [comment]
I've gone ahead and did some memory profiling using the benchmark @ http://www.hamsters.io/performance using a test size of 2 million I can see that after 30 seconds only 24% of the original data was retained and only 3% of each individual typed array was retained.


![24 percent](https://cloud.githubusercontent.com/assets/2227747/26272354/166f7ca8-3ce4-11e7-9649-aecce3195909.png)

![ss](https://cloud.githubusercontent.com/assets/2227747/26272369/64e7991a-3ce4-11e7-997f-7a1507ae2bca.png)

**Comment by austinksmith** [comment]
This profile data also tells me that what is retained is part of the array buffer for each array, I would need to see more example logic to understand what is unique about your use case that requires forcing the garbage collector to work sooner.

![screenshot from 2017-05-19 22-41-35](https://cloud.githubusercontent.com/assets/2227747/26272374/7ba671ee-3ce4-11e7-8508-80854e7a8128.png)

**Comment by rsmithsa** [comment]
It's definitely an issue in Firefox (and looks like a problem in Chrome as well), I can manually trigger multiple GC's and my results don't get collected. It's a problem because I run into memory allocation issues for subsequent work being handled out side of hamsters.

I'm using the array input to define the number if iterations of work to do and split it up between cores. The work is all returned in one long Float64Array.

I've put together a minimal repro here:: [https://plnkr.co/YK7VnetxPZx6ZEjUx5C1](https://plnkr.co/YK7VnetxPZx6ZEjUx5C1)

Feel free to point me in the right direction if I'm doing something silly.

**Comment by austinksmith** [comment]
Though this is typically outside of the support I would normally give let's take a look at what you're doing and I'll explain the problems you're likely running into and why.

This is your example logic, (I fixed the formatting a bit)

```js

var executeModel = function() {
  let workArr = [];
  
  for (let i = 0; i < 1000; i++) {
    workArr.push(i);
  }
  
  var params = {
    'array': workArr,
  };

  hamsters.run(params, function() {
    var arr = params.array;
    let it, idx = 0;
    for (it; it < arr.length; it++) {
      let calcResults = new Float64Array(20000);
      if (rtn.data.length === 0) {
        rtn.data = new Float64Array(arr.length * calcResults.length);
      }
      rtn.data.set(calcResults, idx);
      idx += calcResults.length;
    }
  }, function (output) {
    // Do some post processing
  }, hamsters.maxThreads, false, 'bypass');
}

```

Immediately I see a few issues, the first issue is that you're using `bypass` as a dataType argument when you an simply define `Float64` since that is your desired output. Doing this will also allow you to stop redefining rtn.data as a new Float64Array since creating so many Float64Arrays within your loop is most likely the cause of your memory leak. Additionally you should make sure you are already passing in a Float64Array as your input as well if you can since your output is going to be the same, this will be significantly more performant when communicating with threads.

Here is my cleaned up take on your example, please tweak this where you must and try running it again and let me know if you encounter the same issues.

```js
var executeModel = function() {
  let workArr = [];

  for (let i = 0; i < 1000; i++) {
    workArr.push(i);
  }
  
  var params = {
    array: new Float64Array(workArr),
  };

  hamsters.run(params, function() {
    var arr = params.array;
    let idx, it = 0;
    for (it; it < arr.length; it++) {
      let calcResults = new Float64Array(20000);
      if (rtn.data.length === 0) {
        rtn.data.length = (arr.length * calcResults.length);
      }
      rtn.data.set(calcResults, idx);
      idx += calcResults.length;
    }
  }, function (output) {
     console.log(output);
  }, hamsters.maxThreads, false, 'Float64');
}
```

**Comment by rsmithsa** [comment]
Thanks, I'll have a look and get back to you

**Comment by austinksmith** [comment]
Any luck?

**Comment by rsmithsa** [comment]
Seems to be fine now, thanks for the help
