### ISSUE TITLE
Notifications to main thread from worker or child threads

### ISSUE THREAD

**Issue by lelong37** [austinksmith/Hamsters.js#33]
Team,

Is there away we can send notifications (small payload, with processing info) from the worker threads back to the main thread? e.g. To possibly support providing progress data from threads that are spawned to the main thread? Maybe, allow the ability to pass in another callback for notifications.

**Comment by austinksmith** [comment]
Can you be a little more specific on how you would envision this working?

Currently the library will provide you with error messages from threads if something were to go wrong in your logic.

**Comment by austinksmith** [comment]
@lelong37 Is this still of interest?
