### ISSUE TITLE
how to access outside function from hamsters.run

### ISSUE THREAD

**Issue by darkworks** [austinksmith/Hamsters.js#37]
hi am processing canvas large data so to speedup things am trying to use hamsters for the first time 

so my question is that my outside functions are not accessible within  hamsters.run
example

```
this.testfun = function(val){
 // do something and return 
};

   hamsters.run(params, function() {
     // my code calling function  testfun  but it giver error undefined.  
    }, function(output) {
      console.log(output);
    }, hamsters.maxThreads, true);
```

thanks

**Comment by austinksmith** [comment]
@darkworks Thanks for using the library however please in the future please follow the provided issue template when submitting tickets, it makes it much easier for me to keep track of them down the road. 

The issue you are facing is that threads are sandboxed environments so you cannot share scope with the main thread, I know this is counter intuitive at first but it's actually a good thing in the sense of thread safety and ensuring parallel tasks don't conflict with one another. This will change somewhat down the road as JavaScript adds support for Atomic operations for now though you have a few options to accomplish what you want here.

You can either do the following and simply make your function testFun and modify the inside of testFun to make use of the internal params object.

```js
this.testfun = function(val) {
 // do something and return using params and rtn.data 
};

hamsters.run(params, testFun, function(output) {
  console.log(output);
}, hamsters.maxThreads, true);
```

Or you can just define testFun inside your hamsters function.

```js
hamsters.run(params, function() {
 var testfun = function(val) {
   // do something and return
 };
 rtn.data.push(testFun(value));
}, function(output) {
  console.log(output);
}, hamsters.maxThreads, true);
```

**Comment by austinksmith** [comment]
Take a look at the logic from lzwFloss for an example of how you can define functions to be used within hamsters. 

https://github.com/austinksmith/lzwFloss.js/blob/master/lzwFloss.js

**Comment by darkworks** [comment]
hmmm i used this : https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function

to pass function body in text in paramas and it worked :) 

example : 
```
 var params = {
addfun : 'return a+b',
};

    hamsters.run(params, function() {
var addfun = new Function('a','b',params.addfun);
// now addfun can be used inside.
};
```

**Comment by austinksmith** [comment]
Closing this issue.
