### ISSUE TITLE
Looking for feedback,  what are you using Hamsters.js for?

### ISSUE THREAD

**Issue by austinksmith** [austinksmith/Hamsters.js#38]
Thank you for your interest in the library, I am opening this issue ticket to try to get a better grasp from the community for what use cases they have for the library and what features they think would be useful to add to the library.

If you are currently using the library please respond to this with the format below and let me know what you think, thank you!

# _What are you using the library for?_

# _Has the library helped your use case?_

# _How could the library be improved for your use case?_

# _Any suggestions?_

**Comment by darkworks** [comment]
Am using this library with html5 canvas for image processing , i have to process 5K plus resolution images so to speed pixel analysis i split up portion of image among various threads , and it end merge their results ....
Feature request : you can get number of threads user CPU can handle it one time using : navigator.hardwareConcurrency  so i was wondering if this library have queue so that upon reaching to limit of CPU thread number the new threads should be created created when  other threads complete their execution , i simple words not to create more than navigator.hardwareConcurrency threads it one time

**Comment by austinksmith** [comment]
@darkworks Thanks for using the library, the library contains a fully functional thread pool and work queue system, you do not *need* to define a maximum number of threads the library will use in your hamsters.init call as it will already detect navigator.hardwareConcurrency when the library is initialized and will fallback to a value of 4 threads if navigator.hardwareConcurrency is not present. 

The library will simply reuse those threads over and over, if you have disabled persistence mode then the library will spawn threads as they are requested. Hopefully that makes sense.

**Comment by darkworks** [comment]
thanks for information :) good to hear :+1:

**Comment by austinksmith** [comment]
@darkworks Be sure to read the wiki pages on that as it explains much better, https://github.com/austinksmith/Hamsters.js/wiki/Thread-Pool-System-&-Configruation

**Comment by Andrews54757** [comment]
@austinksmith Hello, I have seen your library and it looks cool. However, I would like to know what is particularly interesting about your library. Why use hamsters.js instead of other, more lightweight libraries such as [Multithread.js](https://keithwhor.github.io/multithread.js/)? What does Automatic Data Aggregation mean? What is memoization used for?

Thanks,
Andrew S

**Comment by austinksmith** [comment]
@Adrews54757 Please cease and desists the use of the library landing page site design immediately, multithread js tackles concurrency not parallelism. The website and wiki accurately explains your other questions, please consider this a friendly notice to stop the use of the hamsters.io layout / design immediately. I will grant a window of 72 hours to comply. A significant amount of time has gone into this library and the website behind it, if you wish to publish a competing library do not steal functions like this.

```js
function converters(type, data) {
    var types = {
        UInt32: Uint32Array,
        Int32: Int32Array,
        UInt16: Uint16Array,
        Int16: Int16Array,
        UInt8: Uint8Array,
        UInt8clamped: Uint8ClampedArray,
        Int8: Int8Array,
        Float64: Float64Array,
        Float32: Float32Array
    }
    return new types[type](data);
}
```

Or the website assets and layout, your "parody" site will confuse users and harm the adoption of the library.

**Comment by Andrews54757** [comment]
@austinksmith I did not copy any of your code. Even for the website, I handmade. I will NOT retract anything. I did not even mention my own project here at all. Even the converter code, I did not copy. Compare it with yours, and you will see.

**Comment by austinksmith** [comment]
```js
  function processDataType(dataType, buffer) {
    const types = {
      'uint32': Uint32Array,
      'uint16': Uint16Array,
      'uint8': Uint8Array,
      'uint8clamped': Uint8ClampedArray,
      'int32': Int32Array,
      'int16': Int16Array,
      'int8': Int8Array,
      'float32': Float32Array,
      'float64': Float64Array
    };
    if(!types[dataType]) {
      return buffer;
    }
    return new types[dataType](buffer);
  }
```

Looks pretty much the same to me, aside from the return buffer. The library is open source, it's perfectly fine to use pieces of it as long as work is attributed to the original within the code base, a simple code comment would suffice */* Sourced from *library* version *1.2.3* */*.

The website is almost a direct copy of the hamsters.io site, whether it was "made by hand" assets were used that exactly mimic the site already made, this will cause confusion to people who will mistake your landing page as my landing page. I do not want to go further than this comment, you can make another one that doesn't copy the exact theme and style of mine without being in violation of any copyright rules. 

Friendly notice clock starts ticking now. Thanks!

**Comment by Andrews54757** [comment]
@austinksmith I built the converter by HAND. Look at the commit history, you shall see. It was not inspired by you. The website's assets were not yours either, the assets and their individual copyrights were untouched.

https://github.com/ThreeLetters/Accel/tree/gh-pages

**Comment by Andrews54757** [comment]
@austinksmith Can we get back on topic now? Away from my own project? I want to know what is particularly interesting about yours.

**Comment by austinksmith** [comment]
I am closing this issue for archiving purposes, this discussion has derailed and is not in line with what this issue ticket was made for, this is not a place to bash the library in order to promote your own offerings. 

@Andrews54757  You will be contacted should the 72 hour window pass without removing the infringing content.

**Comment by Andrews54757** [comment]
@austinksmith I did not mention my library in any way. You brought the subject up after you looked at my profile. I have no intention to advertise here, as I do not need too. However, please note that I will ignore the 72 hour deadline as I believe that I did nothing wrong. If I get a notice, I shall confer with my legal team to support my project. I will not give into you pressuring me to throw away my hard work. My project was created from scratch, by me, over the course of a week. Compared with your project's lifetime, it is little. However, I believe that I have done much more in that time than for the entire lifetime of any other project. So concluding my comment, I will not give into your demands, if you send a DMCA notice, I shall immediately put a counter-DMCA notice up. Good day to you, I will see you in court if I have to.

Thanks,
Andrew S (ThreeLetters)

**Comment by Andrews54757** [comment]
Public Apology to @austinksmith 

I (Andrews54757), apologise for infringing upon Hamsters.js. I am very sorry, and it will never happen again. I should have known that I have done something wrong, but I was ignorant. I am truly sorry for copying [hamsters.io](http://hamsters.io), and I have fully removed all content deemed infringing. I am very sorry for the inconvenience, and I wish him goodwill.

Andrew S
