### ISSUE TITLE
TransformError couldnt find preset es2015

### ISSUE THREAD

**Issue by hasancanozkan** [austinksmith/Hamsters.js#39]
Hi, I have a RN application and just want to try parallel programming using hamsters.js. First, I created a demo app to try the library. however I am getting a strange error, 
What version of the library --> 4.2.0 
What operating system are you seeing the issue on? --> Windows

Which platform (and or) browser are you seeing the issue on? React Native on andorid

What is the version of the platform (and or) browser you are seeing the issue on? --> RN 48.0

The ERROR : TrasnformError: C//Users.. //node_modules//hamsters.js//build//hamsters.js : Couldn't find the preset 'es2015'  relative to the directory C//Users//.. node_modules//hamsters.js
![img_1301](https://user-images.githubusercontent.com/15143230/30004610-dd30cc10-90d2-11e7-88cc-ee0b877c84e8.JPG)

**Comment by austinksmith** [comment]
That is a new one that I have not yet encountered, take a look at this
issue as it might be related to Babel presets not being installed.

https://github.com/facebook/react-native/issues/8296

If that doesn't help I will dig deeper here in the following days.

**Comment by hasancanozkan** [comment]
I was checking on google about the same error but i havent find any solution yet, If i find, i'll also share and inform you, thanks!

**Comment by hasancanozkan** [comment]
I followed the link you sent, my condition was satisfying this. Then, i realized that in .babelrc which was in main root doesn't include "presets" : es2015 . In order to solve this i did --> npm install --save-dev babel-cli babel-preset-es2015 and added es2015 in .babelrc file.

**Comment by austinksmith** [comment]
Great, let me know if you run into any other issues with the library.
