### ISSUE TITLE
error can't find variable: rtn from app.js

### ISSUE THREAD

**Issue by bacancysejal** [austinksmith/Hamsters.js#47]
handleHamster = () => {
        var params = {
            array:[0,1,2,3,4,5,6,7,8,9]
        };
        hamsters.run(params, function() {
            var arr = params.array;
            arr.forEach(function(item) {
                console.warn('calllll', item)
                rtn.data.push((item * 120)/10);
            });
        }, function(output) {
            console.warn('output', output)
            return output;
        }, 2, false);
    }
here rtn not find.

I am using version : 
    "hamsters.js": "^4.2.1",
    "react": "16.2.0",
    "react-native": "0.52.1",
    "react-native-threads": "0.0.10",

**Comment by austinksmith** [comment]
Do me a favor, this version isn't ready for release yet but give this a shot.

Clone the dev branch of the library and use that (it's a work in progress but should be functional as a test bed for react native fixes).

Import react native threads like you have already

```
import { Thread } from 'react-native-threads';
```

and then do this on your library startup

```
hamsters.init({
  Worker: Thread
});
```

Please report back your results, I'm nearing completion on the next library version and react native support is important, thanks!

**Comment by bacancysejal** [comment]
@austinksmith  
I already import 'react-native-threads' library 


import React, { Component } from 'react';
import {Button, StyleSheet, Text, View} from 'react-native';
import './config';
import { Thread } from 'react-native-threads';
import hamsters from 'hamsters.js';

var startOptions = {
    maxThreads: 2,
     Worker: Thread
};
hamsters.init(startOptions);

export default class App extends Component<{}> {
    state = { messages: [] }
    workerThread = null;

    componentDidMount() {
        this.workerThread = new Thread('./worker.thread.js');
        this.workerThread.onmessage = this.handleMessage;
    }

    componentWillUnmount() {
        this.workerThread.terminate();
        this.workerThread = null;
    }

    handleMessage = message => {
        console.tron.log(`APP: got message ${message}`);
        this.setState(state => {
            return { messages: [...state.messages, message] };
        });
    }

    handleHamster = () => {
        var params = {'array':[0,1,2,3,4,5,6,7,8,9]};
        hamsters.run(params, function(rtn) {
            var arr = params.array;
            arr.forEach(function(item) {
                rtn.data.push((item * 120)/10);
            });
        }, function(output) {
            console.warn('output',output)
            return output;
        }, 2, true);
    }

    render() {
        return (
            <View style={styles.container}>
                <Text style={styles.welcome}>
                    Welcome to React Native Threads!
                </Text>

                <Button title="Send Message To Worker Thread" onPress={() => {
                    this.workerThread.postMessage('Hello')
                }} />

                <Button title="Send Message To Worker Multi Thread" onPress={() => {
                    this.handleHamster()
                }} />

                <View>
                    <Text>Messages:</Text>
                    {this.state.messages.map((message, i) => <Text key={i}>{message}</Text>)}
                </View>
            </View>
        );
    }
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#F5FCFF',
    },
    welcome: {
        fontSize: 20,
        textAlign: 'center',
        margin: 10,
    }
});

Can you Informe me when latest version will available?

**Comment by bacancysejal** [comment]
@austinksmith
I already import 'react-native-threads' library

import React, { Component } from 'react';
import {Button, StyleSheet, Text, View} from 'react-native';
import './config';
import { Thread } from 'react-native-threads';
import hamsters from 'hamsters.js';

var startOptions = {
maxThreads: 2,
Worker: Thread
};
hamsters.init(startOptions);

export default class App extends Component<{}> {
state = { messages: [] }
workerThread = null;

componentDidMount() {
    this.workerThread = new Thread('./worker.thread.js');
    this.workerThread.onmessage = this.handleMessage;
}

componentWillUnmount() {
    this.workerThread.terminate();
    this.workerThread = null;
}

handleMessage = message => {
    console.tron.log(`APP: got message ${message}`);
    this.setState(state => {
        return { messages: [...state.messages, message] };
    });
}

handleHamster = () => {
    var params = {'array':[0,1,2,3,4,5,6,7,8,9]};
    hamsters.run(params, function() {
        var arr = params.array;
        arr.forEach(function(item) {
            rtn.data.push((item * 120)/10);
        });
    }, function(output) {
        console.warn('output',output)
        return output;
    }, 2, true);
}

render() {
    return (
        <View style={styles.container}>
            <Text style={styles.welcome}>
                Welcome to React Native Threads!
            </Text>

            <Button title="Send Message To Worker Thread" onPress={() => {
                this.workerThread.postMessage('Hello')
            }} />

            <Button title="Send Message To Worker Multi Thread" onPress={() => {
                this.handleHamster()
            }} />

            <View>
                <Text>Messages:</Text>
                {this.state.messages.map((message, i) => <Text key={i}>{message}</Text>)}
            </View>
        </View>
    );
}
}

const styles = StyleSheet.create({
container: {
flex: 1,
justifyContent: 'center',
alignItems: 'center',
backgroundColor: '#F5FCFF',
},
welcome: {
fontSize: 20,
textAlign: 'center',
margin: 10,
}
});

Can you Informe me when latest version will available?

**Comment by austinksmith** [comment]
Did you use the dev branch of hamsters? The idea is you validate dev branch
works before its released

**Comment by bacancysejal** [comment]
Hey,

I have done  'npm install hamsters.js --save'.
now I have found the solution for that error and run it and get output.

thank you.

**Comment by austinksmith** [comment]
Which version of the library are you running now? Dev branch isn't on npm yet
