### ISSUE TITLE
Hamsters.js v5.1.1 Error: undefined @ 1522342944715

### ISSUE THREAD

**Issue by WorkMAE** [austinksmith/Hamsters.js#49]
Hi, I am trying to get this library up and running to help with some calculations I am going to be running but I keep getting an undefined error when I try and call hamsters.run.

I have an array of an array of objects, that are nested via d3 prior having it passed into hamsters, I am not sure if that is causing the issue or not, which I would hope not since this is a fairly basic use case, nothing too fancy...

So for instance :
![image](https://user-images.githubusercontent.com/31932842/38102841-77d232be-3352-11e8-8b09-27addabf4f97.png)

and in hamsters, I get a red underline at:

![image](https://user-images.githubusercontent.com/31932842/38102872-9841b6be-3352-11e8-9977-c350ec84a071.png)

Here is the actual code:
```
 this.getScores = function (data) {
                //we are going to utilize a library called hamsters for multithreading support
                let params = {
                    myParams: data,
                    threads: 4
                };

                hamsters.run(params, function () {
                    for (var i = 0; i < params.myParams; i++) {
                        //now we do the calculations in here
                        console.log(params);
                    };
                });
```

Any help would be appreciated, I would like to have multithreading support for this project as there are quite a lot of calculations that are going to be needed

**Comment by austinksmith** [comment]
Please provide what `data` looks like

```
    let params = {
                    myParams: data,
                    threads: 4
                };
```

**Comment by WorkMAE** [comment]
I used a promise and this is the error I get:

![image](https://user-images.githubusercontent.com/31932842/38103585-bb102f0c-3354-11e8-8410-801f935e84bc.png)

**Comment by WorkMAE** [comment]
Here is a better overview of what the data looks like:

![image](https://user-images.githubusercontent.com/31932842/38103804-5d4bcbd2-3355-11e8-9fbc-02a1b7d0242c.png)

Its sorted first by employee name, then by Company and then by Month...so the operations are going to be done within the data in the lowest levels

**Comment by WorkMAE** [comment]
Hmm...I tried with just a basic array like in the examples and I still get the "scaffold is not defined" error when using a promise...it appears that it is not an issue with the array itself but with something else

**Comment by WorkMAE** [comment]
seems like an installation issue...I did not upload the src directory to the server...does this need to be in any special place or just in the same location as hamsters.js?  I've never actually had to do anything like this before, typically I just reference the js library and add it to the index page...

**Comment by WorkMAE** [comment]
I'm not using node, I'm assuming I want the build version hamsters.web.min.js?  

Do  I still need to upload the stuff in the source directory?

**Comment by austinksmith** [comment]
Please recreate this ticket following the provided template that is in the modal when you created it. Do not simply remove the template.
