### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by WorkMAE** [austinksmith/Hamsters.js#50]
Thank you for using Hamsters.js! In order to best assist you please follow the guidelines laid out below as they will help significantly in resolving your issues. Tickets that do not follow the provided issue template have less than satisfactory information to resolve the problem reported and will therefore not receive priority support.

### Be polite and courteous 

Attitude goes a long way, while we do our best to ensure the library is problem free it is a very complicated library that encapsulates many features all while trying to support as many platforms as possible. Inevitably some issues may prop up from time to time, patience, understanding, and collaboration are the best ways to resolve bugs in a timely manner.

### New Issue Report

* 5.1.1 and 5.0.0

This will help narrow down the issue you are facing to a specific release of the library, as your issue may be resolved in previous or latter releases.

* Windows 7

Feature support can vary wildly and any issues you are facing may be exclusive to a specific operating system or even a specific version of an operating system.

* Chrome Version 63.0.3239.84 (Official Build) (32-bit)

Some issues may be isolated to specific environments or systems, an issue you are facing in Node.js for example may not be applicable to React Native.

* I am using angularjs 1.50 as the main framework, no node. I am attempting to follow the HTML directions but am confused because it tells me to download the latest build and then install the source directory on the server.  However there are so many variations of files, I feel the instructions are not as clear as they could be for someone who isn't familiar with these processes--typically I install the build versions in most branches.  Typically the only thing you need to do is reference a single library in HTML, without the need to multiple other pieces of code included.  I have tried several ways of installing this but I still can't get it working even with the SRC library installed on the server.

Feature support can vary wildly and any issues you are facing may be exclusive to a specific browser or framework and specific versions of a browser or framework.

* I don't believe the logic is the issue, I believe me not having it installed properly is the issue, can you please provide more detailed instructions as to how to install this without node via regular HTML?

Being able to reproduce an issue directly goes a very long way towards debugging issues with the library, having example logic is probably the most important step you can take towards helping us resolve your issues.

**Comment by austinksmith** [comment]
Take a look at the source on this page..the library is just included using a normal script tag.

https://www.hamsters.io/examples/collatzconjecture

```js
<script type="text/javascript" src="../javascripts/benchmark/hamsters.min.js"></script>

**Comment by austinksmith** [comment]
Use this file https://www.hamsters.io/javascripts/benchmark/hamsters.min.js

**Comment by austinksmith** [comment]
Actually...did you ever run...`hamsters.init();` ?

**Comment by WorkMAE** [comment]
no...I haven't ran hamster.init()

**Comment by austinksmith** [comment]
You should probably try that..

**Comment by WorkMAE** [comment]
OK...I see it is trying to load and then it says its ready, but then gives me the same error and a bunch of 404 errors to /common/rnHamstersWheel.js

![image](https://user-images.githubusercontent.com/31932842/38109598-a833b388-3366-11e8-83f5-a9c72bbba213.png)

**Comment by austinksmith** [comment]
I'm going to reopen this issue, it took a while but I managed to track down the problem with promises and will have a new release ready here shortly that fixes them and will also improve performance as I've found a way to precompute more of the library operations on initialize so latency should be lower when running logic
