### ISSUE TITLE
Tests not pasing

### ISSUE THREAD

**Issue by andreujuanc** [austinksmith/Hamsters.js#54]
Cloned the repo, dev.
npm install
npm run test

OS: Windows 10.

Here is the resport.
https://pastebin.com/8AL6yaHQ

~~Also it does not build. Havent digged why yet.~~
It's caused by rm and cp commands, which does not exists in windows. Most of these issues might be fixed by using a more recent webpack version and a couple of plugins to move things around and delete/clean folders. 

Cheers

**Comment by austinksmith** [comment]
Ah yeah, I use Ubuntu/MacOS/Unix for my development so I never wrote with Windows 10 testing in mind, I just ensured to test before publishing each build. Thanks for the report, I'll look into it once I get back to working on the library.
