### ISSUE TITLE
React-native android side, typeerror using hamsters and react-native-threads

### ISSUE THREAD

**Issue by ingviso** [austinksmith/Hamsters.js#55]
Hello

I'm getting error message using hamsters and react-native-threads. I'm able to use both but still get typeError.
### New Issue Report

* ***What version of the library are you using?***
react-native: 0.55.2
react-native-threads: 0.0.13
hamsters: 5.1.1

* ***What operating system are you seeing the issue on?***
Android / React-native

I'm able to call up the worker and it does it's job but I get this typeError message, so I'm not sure if I'm benefitting from using hamsters or not. 
```
Hamsters.js v5.1.1 Info: Preparing the hamster wheels & readying hamsters @ 1542796747783
hamsters.node.min.js:1 Hamsters.js v5.1.1 Info: 16 Logical Threads Detected, Spawning 16 Hamsters @ 1542796747784
CameraScreen.js:547 TypeError: f.default.SharedWorker is not a constructor
    at e.value (hamsters.node.min.js:1)
    at e.value (hamsters.node.min.js:1)
    at e.value [as init] (hamsters.node.min.js:1)
    at CameraScreen.js:540
    at tryCallOne (core.js:37)
    at core.js:123
    at JSTimers.js:295
    at _callTimer (JSTimers.js:152)
    at _callImmediatesPass (JSTimers.js:200)
    at Object.callImmediates (JSTimers.js:464)
```

The code I use to call upp the hamster is: 

```
hamsters.init({
                     maxThreads: 16,
                     Worker: this.workerThread.postMessage( workerMessage )
                   })
```

Is there some better way of using react-native-threads and hamsters together ?

**Comment by austinksmith** [comment]
Could you do me a favor and post where you are defining, ``` this.workerThread ``` as well, thanks!

**Comment by ingviso** [comment]
Hey sry for the late reply

```
import { Thread } from 'react-native-threads';

workerThread = null;

  async componentWillUnmount() {
    if (Platform.OS === 'android') {
      this.workerThread.terminate();
      this.workerThread = null;
    }
  }

async componentDidMount () {
    if (Platform.OS === 'android'){
      this.workerThread = new Thread('../../worker.thread.js');
      this.workerThread.onmessage = this.handleMessage;
    }
  }

handleMessage = message => {
    this.setState(state => {
      return { workerMessages: [...state.workerMessages, message] };
    });
  }
```

I will then only use:
```
hamsters.init({
                     Worker: this.workerThread.postMessage( workerMessage )
                   })
```

**Comment by austinksmith** [comment]
Can I also see what the contents of ``` worker.thread.js``` are? 

Your init call should look more like this..

```
  hamsters.init({Worker: Thread});

```

Instead of doing a postmessage

**Comment by austinksmith** [comment]
Hamsters.js will handle communication between the threads automatically when you make a function call using the library so you shouldn't do anything with ``` new Thread ``` or ``` workerThread.onmessage ``` as Hamsters.js does it's own onmessage stuff

**Comment by ingviso** [comment]
Should I maybe skip the react-native-threads altogether and just use hamsters, within the worker I'm calling up a native function. 


This is my worker.thread.js
```
import React, { Component } from 'react';
import {
  Button,
  StyleSheet,
  NativeModules,
  Text,
  View
} from 'react-native';
import { self } from 'react-native-threads';

const mediaProcessing = NativeModules.MediaProcessing;

self.onmessage = inputMessage => {
  var inputData = inputMessage.split(',');

  var inputUri     = inputData[0];
  var processedPath = inputData[1];
  var mediaID       = inputData[2];

  var processingFinished = mediaProcessing.run(
        inputUri,,
        processedPath,
        mediaID
      );

  workerMessage = "id:" + mediaID + ",finished:true";
  self.postMessage(workerMessage);
}
```

Maybe better then ?
```
hamsters.init({
               Worker: mediaProcessing.run(inputUri, processedPath, mediaID);
             })
```

**Comment by austinksmith** [comment]
So I think you need to rethink the way you're using the library a bit. 

https://www.hamsters.io/wiki#react-native

```js
  import Worker from '...';
  import hamsters from 'hamsters.js';

  hamsters.init({
    Worker: Worker
  });
```

So this will give you a Worker or Thread to work with right, and when you initialize the library the library will take that web worker object and will spawn the threads you are going to access.

When using the library you won't need to define a separate worker file but instead just define your function in a way that the library can use it. Basically in your main file you'll define the variables you want to message into a threads context and the library will automatically handle communication back and forth for you. so your data would look more like this...


```js
  var inputData = inputMessage.split(',');
  var params = {
     inputUri: inputData[0],
     processedPath: inputData[1],
     mediaID: inputData[2]
  };
 hamsters.run(params, function() {
   //Logic that processes the data passed in params object, access via params.inputUri etc.

 }, function(results) {
   // Handle results from worker(s) and do something with it.
 });
```

**Comment by austinksmith** [comment]
Here's more info on importScripts - https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/importScripts

**Comment by ingviso** [comment]
Great thanks I will test this.

**Comment by ingviso** [comment]
Still not sure on how I should be using the third party workers, the only worker package that is maintained in react-native is react-native-threads. 
For that to work you have to have a separate file that is your worker -> worker.thread.js and to invoke that inside the main code you have to use:
`workerThread = new Thread('../../worker.thread.js');`

So if I use 
```
var inputData = inputMessage.split(',');
var params = {
     threads: 1,
     importScripts: NativeModules.MediaProcessing,
     inputUri: inputData[0],
     processedPath: inputData[1],
     mediaID: inputData[2]
  };
```
```
const workerThread = new Thread('../../worker.thread.js');
hamsters.init({
      Worker: workerThread
})

hamsters.run(params, function() {
    const mediaProcess = params.importScripts;

 }, function(results) {
   // Handle results from worker(s) and do something with it.
 });
```

hamster.init still give me typeerror. 

Can you give me an example on how to use some third-party worker with hamster in react-native

**Comment by austinksmith** [comment]
Can you email me a copy of your project and I can take a look at it? austin@asmithdev.com

**Comment by austinksmith** [comment]
Is version 5 working for you? I'm going to spend some time this week to try to address all the outstanding issues with the library and this should all be resolved in version 5.1.2

**Comment by austinksmith** [comment]
@ingviso Can you do me a favor and give the current dev branch a try? Thanks

**Comment by austinksmith** [comment]
Give v5.1.2 a shot and report back https://github.com/austinksmith/Hamsters.js/releases/tag/v5.1.2 thanks

**Comment by ingviso** [comment]
Sorry for the late reply just saw your email. Do you want me to try with rn
workers ? I want be able to do it until on monday

Best
Ingvi

**Comment by austinksmith** [comment]
I suggest using this https://github.com/joltup/react-native-threads

and then you can do something like...


```js
import { Thread } from 'react-native-threads';

hamsters.init({
 Worker: Thread
});
```

then you should be able to write your logic doing something like..

```js
hamsters.promise({array: 1, 2, 3, 4]}, function() {
   rtn.data.push(1);
}).then(function(output) {
   console.log(output);
});
```

**Comment by austinksmith** [comment]
Really I need to update the wiki but I created a custom worker scaffold specifically around using react-native-threads and the library will try to use that scaffold within the react native environment.

You can view that file here..  https://github.com/austinksmith/Hamsters.js/blob/dev/src/core/common/rnHamstersWheel.js

You can see it imports self from react-native-threads so it expects you to use that library. Though you might be able to trick the library into using the browser or node scaffold if you play around with your hamsters.init stuff but the reason I created the react-native-threads one is because react native doesn't support dataBlobs and thus you have to use serialization to communicate back and forth so that scaffold is designed to only use strings for communication.

**Comment by austinksmith** [comment]
https://github.com/austinksmith/Hamsters.js/issues/67

**Comment by austinksmith** [comment]
Please give the latest version of Hamsters.js a try https://github.com/austinksmith/Hamsters.js/releases/tag/v5.1.3

**Comment by austinksmith** [comment]
I've just finished fixing react native support in https://github.com/austinksmith/Hamsters.js/releases/tag/v5.3.3 and am releasing a version of https://github.com/austinksmith/reactNativeHamsters which will provide real threading support, marking this as resolved. 

Please follow the updated wiki to get this working
