### ISSUE TITLE
rtn data is pushed on different index than 0

### ISSUE THREAD

**Issue by darkworks** [austinksmith/Hamsters.js#58]
so i have replaced v4.2 with  v5.1.1 and i noticed few new things one is "data" key in  rtn return object earlier it was just 0 index i fixed by adding ['data'] in code to extract the thread data which is pushed it index 0 for single thread , however the another strange thing i noticed when we create multiple threads then rtn push  data on index which is same thread number , i wonder it will be good if all threads push its data index 0 is v4.2.2 was doing or any fix for it 

* ***What version of the library are you using?***

v 5.1.1

* ***What operating system are you seeing the issue on?***

windows 7 

* ***Which platform (and or) browser are you seeing the issue on?***

apache , chrome v70

* ***What is the version of the platform (and or) browser you are seeing the issue on?***

chrome v70

* ***Example logic***

![image](https://user-images.githubusercontent.com/12841788/49425730-52d0d780-f7c0-11e8-98c9-2db67782682b.png)

**Comment by austinksmith** [comment]
I'm working on fixing issues found in 5.1.1, I would probably stick to the 5.0.0 or lower versions until 5.1.2 is out, there seems to be several issues that need fixed in 5.1.1, definitely strange and I'm wondering it might have something to do with my webpack config and the optimize order plugin

**Comment by darkworks** [comment]
ok for now i have handled the situation  for checking for valid index  like 

```
		let active_index = 0;
	for(var k=0; k< nthreads; k++){
		if(typeof ctdata['data'][k] != 'undefined'){
			active_index = k;
			break;
		}
	}
```

so finger crossed will wait for next release to patch up the issues

**Comment by darkworks** [comment]
sure i will test it and will let u know 

thanks

**Comment by darkworks** [comment]
ya now its good not getting undefined messages , however persistence mode lib is still breaking when its set false ,  however am using persistence mode as now lib memory is issue fixed its releasing memory on v4.2 it was not releasing

**Comment by austinksmith** [comment]
I've fixed persistence mode off and on and legacy support off and on modes, there are only 2 issues left I've identified but if you try the current dev branch again you should see that putting ``` persistence: false ``` will not break anymore. You can also force legacy mode by doing ``` legacy: true ```

**Comment by austinksmith** [comment]
So you will want to update your copy of the dev branch, it's gone through some significant changes the last couple days and I've now resolved all the outstanding bugs that I'm aware of, though now I've run into some issues with my automated test configuration regardless I've tested a ton of different thread counts and max thread limits and persistence mode off and on, and legacy mode off and on and identified a bug in the momoizer class as well as a few other fixes and things that should improve performance slightly. 

5.1.2 will be officially released once I figure out what's going on with the testing configuration issues and do a few more verification checks/tweaks on how the library is operating behind the scenes. So consider this like a 5.1.2 beta version you can use for now and feel free to report any problems you get.

**Comment by darkworks** [comment]
that's good . 

thanks

**Comment by darkworks** [comment]
i tested your new build its giving again  undefined error 

![image](https://user-images.githubusercontent.com/12841788/49940707-2163b480-ff02-11e8-80e3-ff996af00db8.png)

**Comment by austinksmith** [comment]
v5.1.2 is live, I validated both modes in node.js and firefox/chrome/microsoft edge https://github.com/austinksmith/Hamsters.js/releases/tag/v5.1.2

**Comment by austinksmith** [comment]
V5.1.2 is live on the hamsters.io site benchmark examples and is working fine, try using the hamsters.web.js file it looks like you’re using the node one in the browser? 

Node file is compiled differently when I build the final output and shouldn’t be used in the browser

**Comment by darkworks** [comment]
ya i was using node one , switched to web.min  its again giving old error 

`Uncaught TypeError: _hamstersWebMin2.default.init is not a function`

i will test on sample test branch then hopefully will mail you 

thanks

**Comment by austinksmith** [comment]
Download 5.1.2 latest release, or just use the copy that's running on the hamsters.io site...it should be exactly the same.

https://www.hamsters.io/javascripts/benchmark/hamsters.min.js

you can see how it runs in the benchmark logic it just says ```hamsters.init()``` without passing any startup options

**Comment by darkworks** [comment]
i have mailed your hamster test of v5.1.2 with webpack build can you please review 

thanks

**Comment by austinksmith** [comment]
If you like the project and the support provided please consider donating to help fund the project, I've been working on this library for quite a while and doing what I can to fix bugs and help others get up and running and have yet to receive any donations. I'd like to be able to purchase some higher core count machines and validate the library works properly for those one day..

https://opencollective.com/hamstersjs
