### ISSUE TITLE
Use dev branch version!!

### ISSUE THREAD

**Issue by austinksmith** [austinksmith/Hamsters.js#6]
A bug was discovered in transferrable object support in the most recent released version, the development branch resolves this issue but is not complete in regards to memoization yet. A new release will be out shortly that resolves all remaining discovered bugs.

**Comment by linusnorton** [comment]
Any update on that new version?

**Comment by austinksmith** [comment]
@linusnorton Check out https://github.com/austinksmith/Hamsters.js/releases/tag/v3.9.0
