### ISSUE TITLE
The examples in the website don't have the source code of the example

### ISSUE THREAD

**Issue by fabiosantoscode** [austinksmith/Hamsters.js#60]
(sorry I'm not following the issue template, but the questions there didn't make sense to write down on this page)

I just started reading about the library and would like to see some example code. Now I'll dig through this repo instead.

I thought that the project examples should have the example's source code, or a link to it. It would make the website better!

Cheers!

**Comment by austinksmith** [comment]
I am actually planning to do a rewrite to the website and update the wiki in the latest release version and will take your advice in mind and might provide some example benchmark logic on the page. However in the meantime you can always inspect the page and look at the example logic file https://www.hamsters.io/javascripts/benchmark/collatz_conjecture.js

**Comment by austinksmith** [comment]
I'm going to close this ticket, I'll mark it resolved once the new website version is updated.
