### ISSUE TITLE
im not getting correct results from the rtn.data object  in hamsterjs v5.1.3

### ISSUE THREAD

**Issue by mdrokz** [austinksmith/Hamsters.js#62]
I am using the hamsterjs library in an webgame im developing and im trying to push my data into the rtn.data object. but the results/output only shows the param object. how do i get eh rtn.data output. here are some pics and code.
![image](https://user-images.githubusercontent.com/33598169/53693547-ffbeee80-3dc7-11e9-8e64-692cca7bd12a.png)

![image](https://user-images.githubusercontent.com/33598169/53693550-0b121a00-3dc8-11e9-83e3-14a7c2cfb6f6.png)

![image](https://user-images.githubusercontent.com/33598169/53693555-149b8200-3dc8-11e9-83cd-e6b43e7208fd.png)

here are the console.log results 

![image](https://user-images.githubusercontent.com/33598169/53693601-b91dc400-3dc8-11e9-8e6c-46e83fff74ca.png)

### New Issue Report

* ***What version of the library are you using?***

I am using hamsterjs v5..1.3

* ***What operating system are you seeing the issue on?***

I am using Windows 10

* ***Which platform (and or) browser are you seeing the issue on?***

I am experiencing this issue on chrome and i am developing an web game.

**Comment by austinksmith** [comment]
It looks like you are using the dev branch version which isn't ready for use yet, try to use the latest release version and report back

**Comment by mdrokz** [comment]
> It looks like you are using the dev branch version which isn't ready for use yet, try to use the latest release version and report back

where can i get the latest release version ?, sorry for late reply

**Comment by austinksmith** [comment]
Either using the releases tab https://github.com/austinksmith/Hamsters.js/releases
or using npm https://www.npmjs.com/package/hamsters.js
or you can select v5.1.2 branch from the main page https://github.com/austinksmith/Hamsters.js/tree/v5.1.2

usually its best to avoid using the dev branch because its usually in a state of change, and sometimes I have to take breaks from developing and cannot guarantee that it's 100% working since some changes take longer to polish. When v5.1.3 is complete though it should be a drop in replacement for v5.1.2 with some added features, bug fixes and performance improvements.

**Comment by austinksmith** [comment]
In the future, i'm planning to also update the website so you can download it directly from there too

**Comment by mdrokz** [comment]
ok i found the latest one and i am using it. but now i am getting an new error. it says Hamsters.js v5.1.2 Error: undefined @ 1551798350002. sorry i am new to hamsterjs and multithreading in general. here are the pics of error and code. 

![image](https://user-images.githubusercontent.com/33598169/53815155-16f80a80-3f87-11e9-9cf7-641c1ba9a39b.png)

![image](https://user-images.githubusercontent.com/33598169/53815173-1f504580-3f87-11e9-82ef-d1e4711c16ac.png)

![image](https://user-images.githubusercontent.com/33598169/53815180-237c6300-3f87-11e9-8941-184582819c2a.png)

**Comment by austinksmith** [comment]
the next release will have better error handling, mainly it looks like you are referencing things in an odd way. Like saying `params[0].d_props`, it's most likely throwing the undefined error since `params[0]` might be something internal to the API and therefore d_props won't be defined. Just use directly `params.d_props` instead of `params[0].d_props`

**Comment by mdrokz** [comment]
> Without knowing what dungeon_props or Dungeon looks like it would be hard for me to figure out what you are doing wrong, however at first glance it appears you are passing everything into the array which you don't need to do.
> 
> You can just pass params like so..
> 
> ```js
> params = {
>   d_props: dungeon_props,
>   Dungeon: Dungeon
> }
> ```
> 
> array is really only neccesary when you are using multiple threads, in your case you really seem to just be trying to put the work onto a single thread which is fine. Now within your thread you should be able to access the properties by saying
> 
> ```js
> var dung = params.Dungeon;
> var props = params.d_props;
> 
> //Do all your logic using what you passed and then you can return the results by saying rtn.data = results, or rtn.data.push(results); if that makes sense. 
> ```

okay i did what you said and dungeon_props is an object and dungeon is an class. but i removed them both and just used an example property like this. 
![image](https://user-images.githubusercontent.com/33598169/53820910-c1295f80-3f92-11e9-89ad-69a0cc1acff5.png)

but its stil throwing me the same error

**Comment by mdrokz** [comment]
Ah yess i finally got it to work. the problem was it was missing internal properties of hamster in the params object. 
![image](https://user-images.githubusercontent.com/33598169/53822975-d0aaa780-3f96-11e9-878b-02f8eb333c84.png)

when i added these properties into the params object. the error disappeared. Thanks so much for helping me. i needed to get multi-threading to work in my game. thanks again

**Comment by austinksmith** [comment]
what do you mean "You cant use any other properties other than array"?

**Comment by austinksmith** [comment]
dataType should be optional, as should aggregate and threads. They should all default to fail safe values when you pass something. You might want to downgrade to v4.20 and try that as there is an oustanding bug that might be causing you some trouble that wont be fixed until next release

**Comment by austinksmith** [comment]
Maybe try passing an empty array in your params alongside your dungeon stuff without threads, dataType or aggregate?

**Comment by mdrokz** [comment]
> Maybe try passing an empty array in your params alongside your dungeon stuff without threads, dataType or aggregate?

i did that didnt work.



> dataType should be optional, as should aggregate and threads. They should all default to fail safe values when you pass something. You might want to downgrade to v4.20 and try that as there is an oustanding bug that might be causing you some trouble that wont be fixed until next release

ok i will try downgrading to v4.20 and report back.



> what do you mean "You cant use any other properties other than array"?

i meant i could only pass an array. no objects or string and etc.

**Comment by austinksmith** [comment]
Take a look at this https://www.hamsters.io/wiki#limitations

Also, a work around you might find is to turn your object into a string like JSON.stringify(object) and then within the thread, do JSON.parse(object)

**Comment by mdrokz** [comment]
> Take a look at this https://www.hamsters.io/wiki#limitations
> 
> Also, a work around you might find is to turn your object into a string like JSON.stringify(object) and then within the thread, do JSON.parse(object)

i tried using strings. but strings dont work as well. :(

**Comment by mdrokz** [comment]
i think i can do it now with this. 
![image](https://user-images.githubusercontent.com/33598169/53829870-2d15c300-3fa7-11e9-9005-8ad725d7517a.png)

**Comment by austinksmith** [comment]
can you post exactly what dungeon_props looks like in raw form? This seems really weird that you are facing this much trouble? What is the error you are seeing just passing it as a string without all the extra stuff?

**Comment by mdrokz** [comment]
> can you post exactly what dungeon_props looks like in raw form? This seems really weird that you are facing this much trouble? What is the error you are seeing just passing it as a string without all the extra stuff?

it seems i was passing objects and string wrong. my bad, now it works i just needed to pass the objects and strings without putting brackets in the array. 
![image](https://user-images.githubusercontent.com/33598169/53858497-78a88b00-4000-11e9-9cde-813836184620.png) 

this is what dungeon_props looks like and now i have no error when i pass it like this.
![image](https://user-images.githubusercontent.com/33598169/53858515-8bbb5b00-4000-11e9-87e6-94d6da2dc1cd.png)

i have a question is there support for passing functions into the param object if not will there be support for storing functions in the params object so we can use the function directly inside the thread?

**Comment by austinksmith** [comment]
There are two options for passing functions, you can directly pass them in the params object, or you can use the importScripts option on initialization. Just remember if you pass it in the params object, it'll be serialized and turned into a string along the way so its usually best just to do that up front to avoid any conflicts and then parse it back using eval or new function, if you use the importscripts option it should

var operator = function () {....};
var params = {
  op: String(operator);
};
new Function(params.op)();

or var params = {
  importScripts: [myscript];
}

you can read more about importscripts here... https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/importScripts

**Comment by austinksmith** [comment]
https://github.com/austinksmith/Hamsters.js/releases/tag/v5.1.1

**Comment by mdrokz** [comment]
> There are two options for passing functions, you can directly pass them in the params object, or you can use the importScripts option on initialization. Just remember if you pass it in the params object, it'll be serialized and turned into a string along the way so its usually best just to do that up front to avoid any conflicts and then parse it back using eval or new function, if you use the importscripts option it should
> 
> var operator = function () {....};
> var params = {
> op: String(operator);
> };
> new Function(params.op)();
> 
> or var params = {
> importScripts: [myscript];
> }
> 
> you can read more about importscripts here... https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/importScripts

got it thanks. i will try this and see
