### ISSUE TITLE
Pointers for use with ReactJS

### ISSUE THREAD

**Issue by shanekoss** [austinksmith/Hamsters.js#63]
Hey hey - very curious to try this with ReactJS - is that possible?

I've tried this:

var Worker = require('webworker-threads').Worker;
var hamsters = require('hamsters.js');

hamsters.init({
 Worker: Worker
});

but webworker-threads doesn't seem to like webpack:

TypeError: exists is not a function

  166 |   dir = process.cwd();
  167 | }
  168 | 
> 169 | if (exists(join(dir, 'package.json')) || exists(join(dir, 'node_modules'))) {
      | ^  170 |   // Found the 'package.json' file or 'node_modules' dir; we're done
  171 |   return dir;
  172 | }

 Anyone know of an alternative?

thanks!

**Comment by austinksmith** [comment]
https://github.com/austinksmith/Hamsters.js/issues/67

**Comment by austinksmith** [comment]
Please give the latest version of Hamsters.js a try https://github.com/austinksmith/Hamsters.js/releases/tag/v5.1.3

**Comment by austinksmith** [comment]
I've just finished fixing react native support in https://github.com/austinksmith/Hamsters.js/releases/tag/v5.3.3 and am releasing a version of https://github.com/austinksmith/reactNativeHamsters which will provide real threading support, marking this as resolved. 

Please follow the updated wiki to get this working
