### ISSUE TITLE
react-native-threads not working.

### ISSUE THREAD

**Issue by Genhain** [austinksmith/Hamsters.js#64]
I supply the Worker and Shared Worker to Hamster and get the following `jsPath.endsWith is not a function` i output the jsPath object and it seems to be a `workerScaffold` instead of the expected string.

* ***What version of the library are you using?***

5.1.2

* ***What operating system are you seeing the issue on?***

macOS Mojave 10.14.5

* ***Which platform (and or) browser are you seeing the issue on?***

React Native.

* ***What is the version of the platform (and or) browser you are seeing the issue on?***

Rn 0.59.4

* ***Other Information***
I am using TypeScript and the latest `react-native-threads` 0.0.16

* ***Example logic***

```js
import hamster from 'hamsters.js'
import { plainToClass } from 'class-transformer'
import { Party } from './Party'
import { Thread } from 'react-native-threads'

hamster.init({
	Worker: Thread,
	SharedWorker: Thread
})

export async function doThing() {
	var params = {
		path: 'http:localhost:3000/api/parties',
		authToken: `Bearer e4793b6c5d26aa6dd370e0531f0ea4b4a6d5063b41075b9b956bc81db4b80bb6`,
		threads: 4,
		aggregate: true
	}

	return await hamster.promise(params, async () => {
		let fetchParties = await fetch(params.path, {
			headers: {
				Authorization: params.authToken
			}
		})

		let responseJson = await fetchParties.json()
		responseJson.parties.map((x) => plainToClass(Party, x)).forEach((x) => Party.persist(x))
	})
}

```

**Comment by austinksmith** [comment]
@Genhain   I apologize for the delayed response on this issue, unfortunately big companies in the software community have engaged in a conspiracy against my constitutional rights and attempts to steal my intellectual property and even blacklist me from employment and have turned my life completely upside down trying to defend myself from these actions. I am working to resolve this situation and hope to continue working on this library in the near future, I will make resolving your issue a priority once i get a legal resolution to this ongoing problem.

**Comment by austinksmith** [comment]
I've just finished fixing react native support in https://github.com/austinksmith/Hamsters.js/releases/tag/v5.3.3 and am releasing a version of https://github.com/austinksmith/reactNativeHamsters which will provide real threading support, marking this as resolved.
