### ISSUE TITLE
react native workers

### ISSUE THREAD

**Issue by drakonkat** [austinksmith/Hamsters.js#65]
Hi, in the documentation hamster say that support react-native multithread.
When i open the documentation i see this:
![image](https://user-images.githubusercontent.com/17176640/64342707-6200e200-cfeb-11e9-95fc-83eab6dd1acb.png)

"there are many of these on npm and github" can you link it? 
I only find one, updated last time 3 yars ago.

There is some pratical example of how to implement hamster with a "worker" library?

**Comment by Bijiabo** [comment]
I am finding multithread worker library for react native too.
There is no library still update and useable.

Sad... :(

**Comment by Bijiabo** [comment]
@drakonkat maybe you can have a look at Node-mobile, I have build successful today.
https://code.janeasystems.com/nodejs-mobile

**Comment by austinksmith** [comment]
@drakonkat @Bijiabo I apologize for the delayed response on this issue, unfortunately big companies in the software community have engaged in a conspiracy against my constitutional rights and attempts to steal my intellectual property and even blacklist me from employment and have turned my life completely upside down trying to defend myself from these actions. I am working to resolve this situation and hope to continue working on this library in the near future, I will make this a priority once i get a legal resolution to this ongoing problem.

**Comment by austinksmith** [comment]
Please give the latest version of Hamsters.js a try https://github.com/austinksmith/Hamsters.js/releases/tag/v5.1.3

**Comment by austinksmith** [comment]
I've just finished fixing react native support in https://github.com/austinksmith/Hamsters.js/releases/tag/v5.3.3 and am releasing a version of https://github.com/austinksmith/reactNativeHamsters which will provide real threading support, marking this as resolved.
