### ISSUE TITLE
ERROR: while initiating hamsters.js [React Native]

### ISSUE THREAD

**Issue by saadkhan6670** [austinksmith/Hamsters.js#66]
### New Issue Report
Hamsters : v5.1.2
"react": "16.8.6",
"react-native": "0.60.5"
"react-native-threads": "0.0.17"

Android

i am trying to implement your library in my application. as said in the wiki i have cloned the latest version of library i.e v5.1.2 and placed its SRC folder in my project and referenced it in my component but getting these errors.
i also even tried installing from Npm but no luck.

**Sample Code:**

![image](https://user-images.githubusercontent.com/6495045/67100237-bbf2eb00-f1d8-11e9-9e6c-0908bb8a14b6.png)

**Error :** 
**While debugger is on** 
![image](https://user-images.githubusercontent.com/6495045/67100557-54896b00-f1d9-11e9-8bdc-4995e5939547.png)

**While debugger is off**
![image](https://user-images.githubusercontent.com/6495045/67100612-6bc85880-f1d9-11e9-97fe-0ec7b764f9fa.png)

i know the above error is discussed here https://github.com/austinksmith/Hamsters.js/issues/48
but i have gone through all the discussion but it haven't concluded any thing fruitful.

**Comment by austinksmith** [comment]
@saadkhan6670  I apologize for the delayed response on this issue, unfortunately big companies in the software community have engaged in a conspiracy against my constitutional rights and attempts to steal my intellectual property and even blacklist me from employment and have turned my life completely upside down trying to defend myself from these actions. I am working to resolve this situation and hope to continue working on this library in the near future, I will make this a priority once i get a legal resolution to this ongoing problem.

**Comment by darkworks** [comment]
use old version 4.1.2  its working ok v5 is broken  am still using v4.1.2

**Comment by austinksmith** [comment]
I plan to release some updates in the near future that will hopefully address all outstanding bugs, however as mentioned in #67 I am in need of new work opportunities and need money at the moment. I have already started the process of building a new website that will actually communicate with the library in the near future and hopefully will provide several things. Such as improved support, better security, better insights into your application and some other new things that will be pretty cool. I will push out a bug fix release once I get the new website design up and running, thanks @darkworks for the help, the new bug fix version I will base off of v4.1.2 and revisit all the changes made between 4.1.2 and the current version to see what changed to cause it to break.

**Comment by austinksmith** [comment]
Please give the latest version of Hamsters.js a try https://github.com/austinksmith/Hamsters.js/releases/tag/v5.1.3

**Comment by austinksmith** [comment]
I've just finished fixing react native support in https://github.com/austinksmith/Hamsters.js/releases/tag/v5.3.3 and am releasing a version of reactNativeHamsters which will provide real threading support, marking this as resolved.
