### ISSUE TITLE
http://www.hamsters.io/ offline

### ISSUE THREAD

**Issue by fabioh8010** [austinksmith/Hamsters.js#72]
When I try to access http://www.hamsters.io/, it give the following message:

![image](https://user-images.githubusercontent.com/20051562/93235797-ef861e80-f775-11ea-8543-4bf5cbd49d60.png)

Is it intentional?

**Comment by austinksmith** [comment]
@fabioh8010 Thanks for the bug report, yes this is intentional for the time being. I am working on updates for the site in my off time from work and the new changes are significant enough that I'd prefer no one be using the site and making new user accounts until those changes are rolled out.

**Comment by austinksmith** [comment]
@fabioh8010 The website is back online, there will be more fixes and changes to it as time goes on so you can create an account, login, and update your profile etc. for the time being but the remaining features aren't active at the moment
