### ISSUE TITLE
Uncaught TypeError: hamsters.run is not a function

### ISSUE THREAD

**Issue by hzjux001** [austinksmith/Hamsters.js#74]
windows 10
edge or chrome
hamsters 5.1.3

<script type="text/javascript" src="resources/hamsters/build/hamsters.web.min.js"></script>

                    console.log(hamsters);//this line is run successed

                    hamsters.run(allstore, function() {
                        Ext.each(allstore,function (row){
                            me.showfilepreviewwindow(row["url"],row["name"])
                        })
                    }, function(results) {
                        console.log(results);
                    });

**Comment by hzjux001** [comment]
hamsters 5.1.3

**Comment by austinksmith** [comment]
In the future please follow the issue ticket format, you have not initialized the library, please read the getting started section of the wiki. You must first initialize the library with hamsters.init() before you can use hamsters.run

**Comment by hzjux001** [comment]
The problem has been solved,Thank you.

**Comment by austinksmith** [comment]
@hzjux001 Ive updated the wiki documentation to highlight this better https://hamsters.io/wiki/initializing
