### ISSUE TITLE
react-native-hamsters/example - undefined is not an object (evaluating 'message.data.data')

### ISSUE THREAD

**Issue by GrabbenD** [austinksmith/Hamsters.js#76]
# Overview
Example provided in https://github.com/austinksmith/react-native-hamsters/tree/master/examples/HamstersJS doesn't work due to:
```
TypeError: undefined is not an object (evaluating 'navigator.userAgent.indexOf')
```

This particular example is using master branch in both react-native-hamsters and hamsters.js

This was tested on a Samsung Galaxy S20+ / Android 11

# Workaround?
The error can be partially worked around with:

```javascript
// globals.js
global.navigator.userAgent = 'React Native';
```

```javascript
// index.js
import { AppRegistry } from "react-native";
import globals from "./globals";
import App from "./App";
```

However this leads to another error:
```
TypeError: undefined is not an object (evaluating 'message.data.data')
```

I've also tried to manually integrate react-native-hamsters@1.0.0 + hamsters.js@5.4.0 in our project but I encountered the same error as above

**Comment by austinksmith** [comment]
@xRiot I've just released version 5.4.1 which resolves this issue, please give it a try and make sure to read the wiki documentation https://hamsters.io/wiki/react-native
