### ISSUE TITLE
Node compatibility

### ISSUE THREAD

**Issue by maharshioza** [austinksmith/Hamsters.js#8]
Issue: Library is not supporting as a Node module. 

Its working only for html file.
I request to make one standard **file/library for nodejs users**.

**Comment by austinksmith** [comment]
Unfortunately this will be quite the under taking and something that makes it more problematic is node doesn't ship with a unified web worker implementation out of the box. The library was designed to be pretty environment agnostic and should in theory function fine within node if you wanted to port it into a node export style library and submit a pull request that would be great. Unfortunately I dont have the time or budget to do so at the moment.

**Comment by austinksmith** [comment]
Try the latest dev branch version, if the regular version doesn't work attempt to use the new react-native supported library file.

**Comment by austinksmith** [comment]
Closing this issue, please make a new request if you are still encountering problems. Thanks.
