### ISSUE TITLE
http://www.hamsters.io/ can't be opened?

### ISSUE THREAD

**Issue by renxin111** [austinksmith/Hamsters.js#9]
I can't open www.hamsters.io/. Is it ok now?

**Comment by austinksmith** [comment]
I appologize for that, I was having some network issues with my isp and the site is back up and running now. You can also access the site through https://hamsters.io

**Comment by austinksmith** [comment]
I will be making a more proper website with better guides and regular announcements here shortly, life has been a little hectic.
